# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

source 'http://git.ops.com/XGN-IOS/xgn.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'RNTestDemo' do

    pod 'XGPhotoBrowser'

end

