# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

source 'http://git.ops.com/XGN-IOS/xgn.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'RNTestDemo' do
    
    # 原生库
    pod "Masonry", "1.1.0"
    pod "MBProgressHUD", "1.1.0"
    pod "CocoaLumberjack", "3.4.2"
    
    # npm库
    pod "XGPhotoBrowser", "0.1.3"

end

